{"name": "Удалить курьера. Удаление несуществующего курьера возвращает сообщение об ошибке", "status": "passed", "description": "тест ручки \"Удалить курьера\"", "start": 1724853580979, "stop": 1724853581021, "uuid": "a8320080-0da6-46f5-83a6-67f841381c59", "historyId": "cd5530cef3249ad0d627d00f5554d7a0", "testCaseId": "cd5530cef3249ad0d627d00f5554d7a0", "fullName": "tests.TestDeleteCourier#test_try_delete_non_existing_courier", "labels": [{"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "FanatovPC"}, {"name": "thread", "value": "31284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}