{"name": "Принять заказ. Попытка принять заказ с несуществующим id заказа возвращает корректное сообщение об ошибке", "status": "passed", "description": "тест ручки \"Принять заказ\"", "start": 1724853583535, "stop": 1724853583684, "uuid": "05961e33-a86a-4eb8-a7b1-e6006820fdba", "historyId": "c1ef2f9f1e5cbcef633aecb59356fce3", "testCaseId": "c1ef2f9f1e5cbcef633aecb59356fce3", "fullName": "tests.TestAcceptOrder#test_try_accept_order_non_existing_order_returns_correct_status_code", "labels": [{"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "FanatovPC"}, {"name": "thread", "value": "31284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}