{"name": "test_try_delete_empty_id", "status": "failed", "statusDetails": {"message": "AssertionError: assert {'code': 404,... 'Not Found.'} == {'code': 404,...ния курьера.'}\n  \n  Omitting 1 identical items, use -vv to show\n  Differing items:\n  {'message': 'Not Found.'} != {'message': 'Недостаточно данных для удаления курьера.'}\n  Use -v to get more diff", "trace": "self = <tests.TestDeleteCourier object at 0x000001EFA106DD00>\n\n    def test_try_delete_empty_id(self):  # Ошибка АПИ Яндекса. Обратитесь к куратору Исканов Камил.\n        response = requests.delete(f'{DATA.Url.MAIN_URL}{DATA.Api.DELETE_COURIER}')\n>       assert response.json() == DATA.Results.DELETING_COURIER_EMPTY_ID\nE       AssertionError: assert {'code': 404,... 'Not Found.'} == {'code': 404,...ния курьера.'}\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Differing items:\nE         {'message': 'Not Found.'} != {'message': 'Недостаточно данных для удаления курьера.'}\nE         Use -v to get more diff\n\ntests.py:126: AssertionError"}, "start": 1724779331149, "stop": 1724779331179, "uuid": "0b047f46-3bf9-44c2-b51a-a20291827197", "historyId": "f6b725dbc7ddd2c325b7b65cd42a0a7a", "testCaseId": "f6b725dbc7ddd2c325b7b65cd42a0a7a", "fullName": "tests.TestDeleteCourier#test_try_delete_empty_id", "labels": [{"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "FanatovPC"}, {"name": "thread", "value": "27952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}